object NavBarItem: TNavBarItem
  AlignWithMargins = True
  Left = 0
  Top = 0
  Width = 280
  Height = 34
  Margins.Left = 16
  Margins.Top = 0
  Margins.Right = 0
  Margins.Bottom = 0
  Color = clWhite
  ParentBackground = False
  ParentColor = False
  TabOrder = 0
  object pnlMenuGroupHeader: TPanel
    Left = 0
    Top = 0
    Width = 280
    Height = 34
    Margins.Left = 0
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alClient
    Alignment = taLeftJustify
    BevelOuter = bvNone
    Caption = 'Clientes'
    Locked = True
    ParentColor = True
    TabOrder = 0
    object ShapeItemBackground: TShape
      Left = 0
      Top = 0
      Width = 280
      Height = 34
      Align = alClient
      Brush.Color = 15986415
      Pen.Color = 15986415
      Shape = stRoundRect
      OnMouseDown = ShapeItemBackgroundMouseDown
      OnMouseEnter = ShapeItemBackgroundMouseEnter
      OnMouseLeave = ShapeItemBackgroundMouseLeave
    end
    object LabelItem: TLabel
      Left = 24
      Top = 9
      Width = 27
      Height = 15
      Caption = 'Item'
      Color = clDefault
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 5456182
      Font.Height = -12
      Font.Name = 'Segoe UI'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      OnClick = LabelItemClick
      OnMouseEnter = LabelItemMouseEnter
      OnMouseLeave = LabelItemMouseLeave
    end
  end
end
